name: Deploy dbt Docs

on:
  push:
    branches:
      - main  # Chạy khi push code lên main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install dbt-core dbt-bigquery  # đổi adapter phù hợp

      - name: Build dbt docs
        run: |
          dbt deps
          dbt compile
          dbt docs generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
